### ISSUE TITLE
example of your configs ? 

### ISSUE THREAD

**Issue by MasterCATZ** [automorphism88/snapraid-btrfs#3] opened 2019-11-25 02:14 UTC
unsure why it has taken me 2 years to see this :P 

I use snapper on each of my btrfs drives with snapraid 

so btrfs can help me undo any oops's and snapraid ( hopefully ) can reconstruct any failed hardware , still unsure if its even backing up as its 

WARNING! Ignoring mount point '/mnt/SnapRaidArray/SRD20NA1B19/.snapshots' because it appears to be in a different device

with the 

/etc/snapper/configs
I have separate configs for each drive ( unsure if this is right or wrong ) ie)
SRD13NA1B12  SRD17NA1B16  SRD20NA1B19  SRD5NA1B4  SRD9NA1B8

which contains 
SUBVOLUME="/mnt/SnapRaidArray/SRD13NA1B12"

then snapraid.conf has 
data d13 /mnt/SnapRaidArray/SRD13NA1B12

will snapraid-btrfs just look up /etc/snapper/configs and find which drives are mentioned in snapraid.conf or do I have to specify ? or does it look @ snapraid.conf and then works out the /.snapshots ? 

also you mentioned its best for 

SnapRAID "content" files are stored on data drives, create a dedicated subvolume for them

how would I go about changing this ?
snapraid.conf
data d13 /mnt/SnapRaidArray/SRD13NA1B12

do I just 
btrfs subvolume create /mnt/SnapRaidArray/SRD13NA1B12/content
snapraid.conf
data d13 /mnt/SnapRaidArray/SRD13NA1B12/content/

and snapper / snapraid-btrfs will ignore /content ?

and I am assuming this will then stop all these errors?

Unexpected size change at file '/mnt/SnapRaidArray/SRD11NA1B10/SteamLibrary/steamapps/common/World of Warships/replays/tempArenaInfo.json' from 2585 to 2512.
WARNING! You cannot modify files during a sync.
Rerun the sync command when finished.

 as snapraid will then only be using the hourly snapshots ?

*edit* 
oh never mind think I worked it out 
so this is just to allow a roll back if we stuff a scrub up 
snapraid still reads the mounted volume 

snapper list-configs
pretty much lets it work it all out its self automatically :P 

guess I better move those content files , never even considered them using up space 

do you have any daily sync / scrub scripts ? 

hit another snag unsure why as looking at your code this is what it should be running 

snapper -c SRD11NA1B10 ls

Type   | # | Pre # | Date                          | User | Cleanup  | Description | Userdata
-------+---+-------+-------------------------------+------+----------+-------------+---------
single | 0 |       |                               | root |          | current     |         
single | 1 |       | Mon 25 Nov 2019 17:00:00 AEST | root | timeline | timeline    |         

but it fails with 
"is SYNC_ACL set in snapper configuration?"

        # Check that we have read permission for snapshots
        # Try a snapper ls first in case ACLs need to be refreshed
        elif ! { snapper_ls_wrapper "$i" &> /dev/null &&
                     [[ -r "${snapper_subvols[$i]}/.snapshots" ]] ; }
        then
            fatal_error $E_NO_PERMISSION 'No read permission for ' \
                "${snapper_subvols[$i]}/.snapshots" \
                ' - is SYNC_ACL set in snapper configuration?'
        fi
    done
}

aio@aio:/etc/snapper/configs$ snapper -c SRD10NA1B9 get-config
Key                    | Value                        
-----------------------+------------------------------
ALLOW_GROUPS           |                              
ALLOW_USERS            | root aio                     
BACKGROUND_COMPARISON  | no                           
EMPTY_PRE_POST_CLEANUP | yes                          
EMPTY_PRE_POST_MIN_AGE | 1800                         
FSTYPE                 | btrfs                        
NUMBER_CLEANUP         | yes                          
NUMBER_LIMIT           | 50                           
NUMBER_LIMIT_IMPORTANT | 10                           
NUMBER_MIN_AGE         | 1800                         
QGROUP                 |                              
SPACE_LIMIT            | 0.5                          
SUBVOLUME              | /mnt/SnapRaidArray/SRD10NA1B9
SYNC_ACL               | yes                          
TIMELINE_CLEANUP       | yes                          
TIMELINE_CREATE        | yes                          
TIMELINE_LIMIT_DAILY   | 14                           
TIMELINE_LIMIT_HOURLY  | 24                           
TIMELINE_LIMIT_MONTHLY | 12                           
TIMELINE_LIMIT_WEEKLY  | 4                            
TIMELINE_LIMIT_YEARLY  | 2                            
TIMELINE_MIN_AGE       | 1800   

hmmm brute forced the upgrade to  snapper 0.8.3 
it then stopped complaining about the SYNC_ACL       
           
so now that I have a heap of mismatched dependencies getting libc6 2.29 installed
I guess I will have to leave 
Ubuntu 18.04.3 LTS 
and hop into
 Ubuntu 19.04 (Disco Dingo) 
but then I break steam compatibility and I use my snapraid for my game collection 

it seems snapraid is still trying to look through the snapshots even when in the ignore list ? 
exclude /.snapshots/
??? it used to ignore them saying "because it appears to be in a different device"

WARNING! Ignoring special 'fifo' file '/mnt/SnapRaidArray/SRD2NA1B1/.snapshots/4/snapshot/ZFSRaidz2/BACKUP/9full/tmp/tr-test'
WARNING! Ignoring special 'socket' file '/mnt/SnapRaidArray/SRD2NA1B1/.snapshots/4/snapshot/ZFSRaidz2/BACKUP/9full/tmp/wpa_ctrl_10459-0'

another strange thing I have noticed is CPU usage is down to 20% from 100%  
and time taken is a lot longer maybe 1/5 the speed ,
 no real drama because I normally have to adjust the nice value so PC is usable

 800meg read 100meg writes not too bad I guess 
normally 2 gig read  400 meg write which maxed out the I/O my poor CPU could Handle
its like its not doing parallel writes ?

**Comment by automorphism88** [comment] 2019-12-06 01:14
>  I have separate configs for each drive ( unsure if this is right or wrong ) ie)
SRD13NA1B12 SRD17NA1B16 SRD20NA1B19 SRD5NA1B4 SRD9NA1B8

This is correct.

> WARNING! Ignoring mount point '/mnt/SnapRaidArray/SRD20NA1B19/.snapshots' because it appears to be in a different device

This is harmless, and the warning should go away if you add `exclude /.snapshots/` to your `snapraid.conf` file as suggested by the [README](https://github.com/automorphism88/snapraid-btrfs/blob/master/README.md#q-what-about-my-snapraidconf-file-do-i-need-to-do-anything-there). However, this does indicate the README is inaccurate in its description of what will happen if you don't add that line to your `snapraid.conf` file. Looks like the only reason to do as the README recommends is to avoid this warning.

> I have separate configs for each drive ( unsure if this is right or wrong ) ie)
> SRD13NA1B12 SRD17NA1B16 SRD20NA1B19 SRD5NA1B4 SRD9NA1B8
> 
> which contains
> SUBVOLUME="/mnt/SnapRaidArray/SRD13NA1B12"
> 
> then snapraid.conf has
> data d13 /mnt/SnapRaidArray/SRD13NA1B12

This looks correct.

> will snapraid-btrfs just look up /etc/snapper/configs and find which drives are mentioned in snapraid.conf or do I have to specify ? or does it look @ snapraid.conf and then works out the /.snapshots ?

What snapraid-btrfs does is explained in [this section of the README](https://github.com/automorphism88/snapraid-btrfs/blob/master/README.md).

> how would I go about changing this ?
> snapraid.conf
> data d13 /mnt/SnapRaidArray/SRD13NA1B12
> 
> do I just
> btrfs subvolume create /mnt/SnapRaidArray/SRD13NA1B12/content
> snapraid.conf
> data d13 /mnt/SnapRaidArray/SRD13NA1B12/content/
> 
> and snapper / snapraid-btrfs will ignore /content ?
> 
> and I am assuming this will then stop all these errors?

The `btrfs subvolume create` command looks good, but if you do it this way, where the content subvolume is mounted underneath the data subvolume, then you might need to add an `exclude` line for the content directory to prevent getting warnings from SnapRAID. SnapRAID should exclude the content file itself regardless, so it's just about preventing that (harmless) mount point warning.

What I do instead is have a flat subvolume layout where data is stored in `/path/to/drive/data` and content in `/path/to/drive/content`.

> Unexpected size change at file '/mnt/SnapRaidArray/SRD11NA1B10/SteamLibrary/steamapps/common/World of Warships/replays/tempArenaInfo.json' from 2585 to 2512.
> WARNING! You cannot modify files during a sync.
> Rerun the sync command when finished.

You shouldn't see this message when using `snapraid-btrfs` since a read-only snapshot, by definition, can't be modified - unless this particular drive is not managed by `snapraid-btrfs` (see [an explanation here](https://github.com/automorphism88/snapraid-btrfs/blob/master/README.md#q-do-i-need-to-use-btrfs-for-all-of-the-data-drives)). Also doesn't look like a snapshot is being used there so either you're running `snapraid` directly and not via `snapraid-btrfs` or you don't have a snapper config that's being recognized for that drive. This is why the RE

> as snapraid will then only be using the hourly snapshots ?

If you're creating your own snapshots, hourly or otherwise, it has no effect on `snapraid-btrfs`, which will only use snapshots that it creates (keeping track of them using snapper userdata). It will completely ignore any snapshots that don't have its userdata key set, so that it doesn't interfere with any other snapshot scheme you might also use.

> oh never mind think I worked it out
> so this is just to allow a roll back if we stuff a scrub up

It does allow that (well, scrub is read-only, but it will allow you to roll back a bad fix), but that's not the main purpose. That's explained [here](https://github.com/automorphism88/snapraid-btrfs/blob/master/README.md#q-why-use-snapraid-btrfs).

> guess I better move those content files , never even considered them using up space

It's not just a suggestion to put the content files in a different subvolume - `snapraid-btrfs` will actually display an error message and refuse to run if a content file is found in a data subvolume that it's processing (you can see the relevant code [here](https://github.com/automorphism88/snapraid-btrfs/blob/d2a9e6bd86b22750370b28e779b93345311bee4c/snapraid-btrfs#L102)). If you're able to get it to actually snapshot content files and waste space that's a bug in `snapraid-btrfs` and you should open a separate issue about it. That should probably be explained in the README.

> do you have any daily sync / scrub scripts ?

Nothing special. 

> hmmm brute forced the upgrade to snapper 0.8.3
> it then stopped complaining about the SYNC_ACL
> so now that I have a heap of mismatched dependencies getting libc6 2.29 installed

Yeah, mixing and matching Ubuntu versions like that doesn't work. The right way to do this would be to install the newer snapper, along with all of its dependencies, in a chroot or prefix setup, so that you could run the newer version with appropriate dependencies, without overwriting the older system. That's a last resort that shouldn't be necessary here though.

> I guess I will have to leave
> Ubuntu 18.04.3 LTS
> and hop into
> Ubuntu 19.04 (Disco Dingo)
> but then I break steam compatibility and I use my snapraid for my game collection

Ubuntu 18.04.3 shouldn't be old enough to break anything. This script was originally written in 2017. If anything, it might break with a newer version of snapper, the way it did when they changed the order of columns in the `snapper ls` output in version 0.7.0. I see you commented on the other closed issue about this in more detail, but whatever issue you were having, it doesn't look like it's the same one, and I think it's likely not the snapper version causing it, since 0.5.4 should be supported. 

If `snapraid-btrfs` does indeed break in Ubuntu 18.04, that is a bug that I would want to fix. There's not enough information given for me to reproduce any bug that might be present though.

> it seems snapraid is still trying to look through the snapshots even when in the ignore list ?
> exclude /.snapshots/
> ??? it used to ignore them saying "because it appears to be in a different device"
> 
> WARNING! Ignoring special 'fifo' file '/mnt/SnapRaidArray/SRD2NA1B1/.snapshots/4/snapshot/ZFSRaidz2/BACKUP/9full/tmp/tr-test'
> WARNING! Ignoring special 'socket' file '/mnt/SnapRaidArray/SRD2NA1B1/.snapshots/4/snapshot/ZFSRaidz2/BACKUP/9full/tmp/wpa_ctrl_10459-0'

Exclude paths are relative to the base directory. When you run `snapraid-btrfs` that base directory is replaced by the snapshot that's being used for the sync and so what's actually being excluded is `/mnt/SnapRaidArray/SRD2NA1B1/.snapshots/4/snapshot/.snapshots`. See [explanation](https://github.com/automorphism88/snapraid-btrfs/blob/master/README.md#q-what-about-my-snapraidconf-file-do-i-need-to-do-anything-there).

> another strange thing I have noticed is CPU usage is down to 20% from 100%
> and time taken is a lot longer maybe 1/5 the speed ,
> no real drama because I normally have to adjust the nice value so PC is usable
> 
> 800meg read 100meg writes not too bad I guess
> normally 2 gig read 400 meg write which maxed out the I/O my poor CPU could Handle
> its like its not doing parallel writes ?

I'm not sure what's causing this, but I haven't noticed anything at all like that. You might consider asking on the SnapRAID SourceForge page. Maybe fragmentation related? If you do figure it out, I would be interested to know the answer.

**Comment by automorphism88** [comment] 2019-12-06 01:20
As of now I'm keeping this issue open due to the needed fixes/clarifications in the README identified here, but will be closing it once that's done as there aren't any reproducible bugs in the script itself described here and this thread is too cluttered. If you have further questions, you can still ask them here after the issue is closed, but if you have more information about a bug that needs to be fixed in the script and not the documentation, please open a separate issue and keep it to one bug per issue.

**Comment by MasterCATZ** [comment] 2019-12-12 09:12
"This is harmless, and the warning should go away if you add exclude /.snapshots/ to your snapraid.conf file as suggested by the README. However, this does indicate the README is inaccurate in its description of what will happen if you don't add that line to your snapraid.conf file. Looks like the only reason to do as the README recommends is to avoid this warning."

I did mention exclude /.snapshots/ was in /etc/snapraid.conf
 and it was still looking through them for some reason 

anyhow It did not seem to cause any issues and your script did solve the file change issues while doing snapraid tasks, thanks for the indepth reply also

only thing I am trying to work out now is why it keeps going into interactive mode 
it seemed to only start doing this after replacing a failing disk  ,

#sudo snapraid-btrfs scrub

417  | single |       | Thu 12 Dec 2019 18:12:09 AEST | root |          | snapraid-btrfs interactive prompt | snapraid-btrfs=created
Enter a snapshot (0 for none, n for new, q to quit): q



Ubuntu 19.10
snapper --version
snapper 0.8.3
flags btrfs,lvm,no-ext4,xattrs,rollback,btrfs-quota,no-selinux

**Comment by automorphism88** [comment] 2019-12-13 09:28
> I did mention exclude /.snapshots/ was in /etc/snapraid.conf
> and it was still looking through them for some reason

Hmm. I do see that in the configuration that appears in the output posted in your other issue. I've never seen that message show up myself though. I'd be interested to learn why the exclude isn't working as expected. But this warning is caused by the fact that snapraid thinks different btrfs subvolumes are different filesystems, which is also the cause of the known issue mentioned in the README about not being able to use inodes to detect move operations.

> only thing I am trying to work out now is why it keeps going into interactive mode
> it seemed to only start doing this after replacing a failing disk , pretty sure it went foobar after updating snapper to get past SYNC_ACL issue

That menu is displayed if `snapraid-btrfs` cannot find the snapshot it's trying to use, either because an invalid snapshot number was specified, or no snapshot was found to correspond with the selected (or default) rule to pick a snapshot (sync, res, diff, or last). If the `-q`/`--quiet` option is specified, `snapraid-btrfs` will just exit with an error message instead, which was the original behavior in that situation before I added the error recovery. Maybe I should consider making that toggled by a different option instead of `-q`, so that something like a cron job that doesn't want the script to be interactive under any circumstances could disable that behavior without being forced to accept the other effects of `-q` alongside it.

If you just replaced a disk and haven't done a sync with the new disk yet, that would explain why there were no synced snapshots found. For a newly replaced disk, if you're trying to do a scrub before you've created snapshots with a sync, then either `new` or `0` should work, specified either with the `-U` option or with the interactive menu. In your case, it looks like you have one snapshot, that was created using the interactive prompt, and its userdata key is set to created. When you do a scrub, `snapraid-btrfs` looks for the most recent snapshot with its userdata key set to "synced" (i.e. the behavior that `-u sync` implies). This is because you want to scrub using the same snapshots that your parity was last updated with. However, you don't have any snapshots with userdata snapraid-btrfs=synced, so snapraid-btrfs falls back to the interactive prompt.

So either you haven't run a sync yet with that drive (or deleted the snapshot you used, though `snapraid-btrfs cleanup` won't delete the most recently synced, so you would have had to use `snapraid-btrfs cleanup-all` or manually deleted it), or the userdata key wasn't updated properly when you did. If the latter, it's a bug, and you should create a separate issue for it with any relevant information. The userdata key is supposed to be set to "syncing" when a sync operation is started with a snapshot, and "synced" when the sync operation completes successfully. Regardless of the cause, you can avoid getting the interactive menu if you use the `-U` or `-u` option to override the default.

I still don't think you should have needed to update snapper at all, and given the reasons you gave for sticking with Ubuntu 18.04 LTS, you should probably give that another try, since it should be supported. I'm almost positive that whatever changed when you upgraded must have been configuration-related, and not directly related to the snapper version.

The error message about `SYNC_ACL` that you mentioned appears when the user that's running `snapraid-btrfs` doesn't have read access to the snapshots, or can't run a `snapper ls` on a config. Setting the `SYNC_ACL` snapper option causes snapper to set appropriate ACLs so that the user(s) and group(s) specified in `ALLOW_USERS` and `ALLOW_GROUPS` have access, and is mentioned in the error message because it's not as obvious that you need to set it. It does a `snapper ls &> /dev/null` in case the configuration was just changed, since the ACLs aren't actually applied to the filesystem after a configuration change until snapper is actually run on that config. Just testing for read permission would require the user to run a snapper command manually to sync the ACLs, while just testing if the user could run `snapper ls` would not be sufficient since that command will succeed if `ALLOW_USERS`/`ALLOW_GROUPS` is set properly, regardless of whether `SYNC_ACL` isn't enabled.

Check if the user you run `snapraid-btrfs` as is able to run `snapper ls` on the config(s) in question and has read access to the `.snapshots` subvolume on all your drives. If not, then the issue isn't with `snapraid-btrfs`, but is either a snapper bug or an Ubuntu bug (more likely the latter), and should be reported to them. If the error only happens with `snapraid-btrfs` then it's a bug in snapraid-btrfs and you should open a separate issue about it. You could also try commenting out that test at the bottom of the `check_config()` function and seeing what happens. But if your user doesn't have read permission for `.snapshots`, the script will not work anyway (which is the whole reason that check is done), so this would only help if the error message were a false positive somehow.

> while doing a fix for the replaced disk i seemed to have gotten stuck in a loop as well , so i guess better fixing without the btrfs wrapper

I recently fixed an [issue](https://github.com/automorphism88/snapraid-btrfs/issues/2) related to that, did you try with the latest commit? There should be no problem with doing the fix without the wrapper, though you might need to make your own temporary config file to point snapraid to the snapshots on the other disks that you synced with. Running `snapper ls` manually and looking at the userdata should tell you which ones were used, the same way the script finds them by parsing the output of `snapper ls`.

**Closed** 2020-07-30 10:06 UTC
